### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by thejameskyle**

### CODE REVIEW

**Comment by medikoo** [comment]
Tests and lint configuration need to stay in npm package. We may consider filtering `.travis.yml` but it doesn't make much difference (and just for that another file in a repo?), so I'm closing it.

**Comment by thejameskyle** [comment]
Why would tests and lint ever need to stay in the npm package?

**Comment by medikoo** [comment]
It's been discussed here:

https://github.com/medikoo/es5-ext/issues/11
https://github.com/npm/npm/issues/5264

**Comment by thejameskyle** [comment]
re: npm/npm#5264

Considering the npm team uses `package.json#files` for all their repositories I think you should probably follow suit.

**Pull request closed without merging**
